version: '2.0'

services:

  minio:
    image: minio/minio
    restart: unless-stopped
    
    ports:
      - 9000:9000
    volumes:
      - /media/playground:/data
    environment:
      MINIO_ACCESS_KEY: DCFO7M7ZJR4Q681U2DUH
      MINIO_SECRET_KEY: PatXGqpsPyqvgpMd+1w+S3mD6HMiq8mfTxPz8jbD
      MINIO_REGION: us-east-1
      MINIO_HTTP_TRACE: /logs.txt
    command: server /data
    networks:
      - backend   

  avradio: 
    image: labizbille/avradioworkflow:1.0.0.1
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - "s3Storage__bucket=avradioworkflow"
      - "s3Storage__region=us-east-1"
      - "s3Storage__accesskey=DCFO7M7ZJR4Q681U2DUH"
      - "s3Storage__secretkey=PatXGqpsPyqvgpMd+1w+S3mD6HMiq8mfTxPz8jbD"
      - "s3Storage__StorageRoot=articles"
      - "s3Storage__customEndpoint=http://192.168.10.38:9000"
      - "s3Storage__endPointHttp=true"
    networks:
      - backend   

networks:
  backend:

