version: '3'
# for production use run with command: prod -- ./dist/XXXXXX.js

services:
  scriptsholder: 
    build: .
    image: labizbille/radioactions:0.1
#    command: debug -- ./src/test.ts
#    command: prod -- ./dist/src/publishBlog.js RadioWorkflow/2020_05_25_Interview_Sea_ploggers_English
    command: startandwait
    environment:
      - AVRADIO_SSHUSER=radio-kartik
      - AVRADIO_PUBLISHMONITOR=/wpapp/data/pmon
      - AVRADIO_AFTERPUB_FOLDER_0=/playground/done
      - AVRADIO_AFTERPUB_FOLDER_1=/archive
    volumes:
      - ./scripts/src:/scripts/src
      - ./privateData/.ssh/id_rsa:/root/.ssh/id_rsa_toCopy
      - C:\tmp\avWorkflowdata\playground\articles:/playground/
      - ../testdata/archive:/archive/
    ports:
      - 9222:9222

